import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { jsPDF } from 'npm:jspdf@4.0.0';
import { parse } from 'npm:date-fns@3.6.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { studentId } = await req.json();
    if (!studentId) {
      return Response.json({ error: 'Student ID required' }, { status: 400 });
    }

    // Fetch student and subject data
    const student = await base44.entities.SchoolUser.get(studentId);
    if (!student) {
      return Response.json({ error: 'Student not found' }, { status: 404 });
    }

    // Verify parent has access to this student
    const parentUser = await base44.entities.SchoolUser.get(user.id);
    if (!parentUser?.linkedStudentIds?.includes(studentId)) {
      return Response.json({ error: 'Unauthorized access' }, { status: 403 });
    }

    // Fetch all subjects to get subject names
    const subjects = await base44.entities.Subject.filter({ schoolId: student.schoolId });
    const subjectMap = {};
    subjects.forEach(s => {
      subjectMap[s.id] = s.name;
    });

    // Create PDF
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let y = 15;

    // Header
    doc.setFontSize(18);
    doc.setTextColor(51, 51, 51);
    doc.text('Subject Averages Report', pageWidth / 2, y, { align: 'center' });
    y += 10;

    // Student info
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text(`Student: ${student.fullName}`, 15, y);
    y += 6;
    doc.text(`Class: ${student.className}`, 15, y);
    y += 6;
    doc.text(`School: ${student.schoolName}`, 15, y);
    y += 6;
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 15, y);
    y += 12;

    // Table headers
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.setFillColor(70, 130, 180);
    const colWidth = (pageWidth - 30) / 2;
    doc.rect(15, y - 5, colWidth, 7, 'F');
    doc.rect(15 + colWidth, y - 5, colWidth, 7, 'F');
    doc.text('Subject', 17, y);
    doc.text('Average', 15 + colWidth + 2, y);
    y += 10;

    // Table rows
    doc.setTextColor(51, 51, 51);
    doc.setFontSize(10);
    let rowIndex = 0;
    (student.subjectAverages || []).forEach(item => {
      if (y > pageHeight - 20) {
        doc.addPage();
        y = 15;
      }

      const subjectName = subjectMap[item.subjectId] || 'Unknown';
      const average = item.average.toFixed(1);
      const bgColor = rowIndex % 2 === 0 ? [245, 245, 245] : [255, 255, 255];
      
      doc.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
      doc.rect(15, y - 5, colWidth, 7, 'F');
      doc.rect(15 + colWidth, y - 5, colWidth, 7, 'F');
      doc.text(subjectName, 17, y);
      doc.text(average, 15 + colWidth + 2, y);
      y += 7;
      rowIndex++;
    });

    y += 8;
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('This report was automatically generated by the school system', pageWidth / 2, pageHeight - 10, { align: 'center' });

    const pdfBytes = doc.output('arraybuffer');
    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="subject_averages_${studentId}.pdf"`,
      },
    });
  } catch (error) {
    console.error('Report generation error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});